config/routes.rb
Rails.application.routes.draw do
  resources :sql_metrics, :only => [:index, :destroy]
end

app/models/sql_metrics/metric.rb
module SqlMetrics
  class Metric
    include MongoMapper::Document
    
    key :name, String
    key :duration, Integer
    key :instrumenter_id, String
    key :payload, Hash
    key :started_at, DateTime
    key :created_at, DateTime
    
    def self.store!(args)
      metric = new
      metric.parse(args)
      metric.save!
    end
    
    def parse(args)
      self.name = args[0]
      self.started_at = args[1]
      self.duration = (args[2] - args[1]) * 1_000_000
      self.instrumenter_id = args[3]
      self.payload = args[4]
      self.created_at = Time.now.utc
    end
  end
end

app/controllers/sql_metrics_controller.rb
class SqlMetricsController < ApplicationController
  def index
    @metrics = SqlMetrics::Metric.all
  end
  
  def destroy
    @metric = SqlMetrics::Metric.find(params[:id])
    @metric.destroy
    redirect_to sql_metrics_url
  end
end

app/views/sql_metrics/index.html.haml
!!!
%h1 Listing SQL Metrics

%table{:cellspacing=>"10"}
	%tr
		%th Name
		%th Duration
		%th Started At
		%th Payload
		%th
	- @metrics.each do |metric|
		%tr
			%td=metric.name
			%td #{metric.duration}us
			%td #{time_ago_in_words metric.started_at} ago
			%td
				- metric.payload.each do |k,v|
					%p
						%b= k.humanize
						%br/
						= v
			%td= link_to 'Destroy', sql_metric_path(metric), :confirm => 'Are you sure?', :method => :delete
		